language: php

php:
   - 5.6
   - 7.0
   - 7.1

matrix:
  allow_failures:
    - php: 7.0
    - php: 7.1

before_install:
   - composer self-update

install:
   - composer install --optimize-autoloader --prefer-source --no-interaction

script:
   - php vendor/bin/phpunit -c phpunit.xml --color --coverage-clover=build/logs/clover.xml

after_script:
   - wget https://scrutinizer-ci.com/ocular.phar
   - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml
